### ISSUE TITLE
review@0.0.2

### ISSUE THREAD

**Issue by justcppdev** [Spardoks/Stack#2]
![screenshot-github_com-2017-10-22-09-37-45-189](https://user-images.githubusercontent.com/26243572/31858973-1f934f78-b70d-11e7-9211-68fa977c21e4.png)

**Comment by Spardoks** [comment]
В 4 стеке строгость, а это было для 3

**Comment by Spardoks** [comment]
https://github.com/Spardoks/Stack/blob/master/include/Stack.hpp
